// ============================================================
//  DADOS DE EXAMES — Clínica GRO Saúde
//  Atualize este arquivo com os dados reais das agendas.
//  Formato: array de objetos com as colunas abaixo.
// ============================================================

const GRO_EXAMES = [
  // Estrutura de cada registro:
  // { data: "AAAA-MM-DD", tipo: "ASO Admissional", descricao: "Audiometria", empresa: "Empresa XYZ", paciente: "João Silva", status: "Realizado" }

  // ---- JANEIRO 2025 ----
  { data:"2025-01-06", tipo:"ASO Admissional",   descricao:"Audiometria",            empresa:"ABS Infraestrutura",    paciente:"Carlos A.",   status:"Realizado" },
  { data:"2025-01-06", tipo:"ASO Admissional",   descricao:"Acuidade Visual",         empresa:"ABS Infraestrutura",    paciente:"Carlos A.",   status:"Realizado" },
  { data:"2025-01-07", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"GHR Transformadores",   paciente:"Maria B.",    status:"Realizado" },
  { data:"2025-01-07", tipo:"ASO Periódico",     descricao:"Glicemia em Jejum",       empresa:"GHR Transformadores",   paciente:"Maria B.",    status:"Realizado" },
  { data:"2025-01-07", tipo:"ASO Periódico",     descricao:"Colesterol Total",        empresa:"GHR Transformadores",   paciente:"Maria B.",    status:"Realizado" },
  { data:"2025-01-08", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Haras Meirelles",       paciente:"João C.",     status:"Realizado" },
  { data:"2025-01-08", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Haras Meirelles",       paciente:"João C.",     status:"Realizado" },
  { data:"2025-01-09", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Ana D.",      status:"Realizado" },
  { data:"2025-01-09", tipo:"ASO Demissional",   descricao:"Acuidade Visual",         empresa:"Brasilquímica",         paciente:"Ana D.",      status:"Realizado" },
  { data:"2025-01-10", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Cabala Cervejaria",     paciente:"Pedro E.",    status:"Realizado" },
  { data:"2025-01-13", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"CLOMA Funilaria",       paciente:"Lucas F.",    status:"Realizado" },
  { data:"2025-01-13", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"CLOMA Funilaria",       paciente:"Lucas F.",    status:"Realizado" },
  { data:"2025-01-14", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Don Pepper",            paciente:"Fernanda G.", status:"Realizado" },
  { data:"2025-01-14", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Don Pepper",            paciente:"Fernanda G.", status:"Realizado" },
  { data:"2025-01-15", tipo:"ASO Periódico",     descricao:"Espirometria",            empresa:"Fundição Garra",        paciente:"Roberto H.",  status:"Realizado" },
  { data:"2025-01-15", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Fundição Garra",        paciente:"Roberto H.",  status:"Realizado" },
  { data:"2025-01-16", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"GM Empreendimentos",    paciente:"Tânia I.",    status:"Realizado" },
  { data:"2025-01-16", tipo:"ASO Admissional",   descricao:"Glicemia em Jejum",       empresa:"GM Empreendimentos",    paciente:"Tânia I.",    status:"Realizado" },
  { data:"2025-01-17", tipo:"Coleta Laboratorial",descricao:"Hemograma Completo",     empresa:"Mega Impress",          paciente:"Samuel J.",   status:"Realizado" },
  { data:"2025-01-20", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Multi-Grama Paisagismo",paciente:"Carla K.",    status:"Realizado" },
  { data:"2025-01-20", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"Multi-Grama Paisagismo",paciente:"Carla K.",    status:"Realizado" },
  { data:"2025-01-21", tipo:"ASO Retorno",       descricao:"Acuidade Visual",         empresa:"Souza Arantes",         paciente:"Diego L.",    status:"Realizado" },
  { data:"2025-01-22", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Elisa M.",    status:"Realizado" },
  { data:"2025-01-23", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"Trama",                 paciente:"Felipe N.",   status:"Realizado" },
  { data:"2025-01-24", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"WJ Decor",              paciente:"Giovana O.",  status:"Realizado" },
  { data:"2025-01-27", tipo:"ASO Admissional",   descricao:"Raio-X de Tórax",         empresa:"ABS Infraestrutura",    paciente:"Henrique P.", status:"Realizado" },
  { data:"2025-01-28", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Isabela Q.",  status:"Realizado" },
  { data:"2025-01-29", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"GHR Transformadores",   paciente:"Jorge R.",    status:"Realizado" },
  { data:"2025-01-30", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"CLOMA Funilaria",       paciente:"Kelly S.",    status:"Realizado" },
  { data:"2025-01-31", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Don Pepper",            paciente:"Leandro T.",  status:"Realizado" },

  // ---- FEVEREIRO 2025 ----
  { data:"2025-02-03", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Fundição Garra",        paciente:"Marina U.",   status:"Realizado" },
  { data:"2025-02-03", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"Fundição Garra",        paciente:"Marina U.",   status:"Realizado" },
  { data:"2025-02-04", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"GM Empreendimentos",    paciente:"Nelson V.",   status:"Realizado" },
  { data:"2025-02-05", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"Haras Meirelles",       paciente:"Olívia W.",   status:"Realizado" },
  { data:"2025-02-06", tipo:"ASO Periódico",     descricao:"Espirometria",            empresa:"Mega Impress",          paciente:"Paulo X.",    status:"Realizado" },
  { data:"2025-02-07", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Multi-Grama Paisagismo",paciente:"Quésia Y.",   status:"Realizado" },
  { data:"2025-02-10", tipo:"ASO Demissional",   descricao:"Raio-X de Tórax",         empresa:"Souza Arantes",         paciente:"Ricardo Z.",  status:"Realizado" },
  { data:"2025-02-11", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"TC Consult",            paciente:"Sandra A2.",  status:"Realizado" },
  { data:"2025-02-12", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Trama",                 paciente:"Thiago B2.",  status:"Realizado" },
  { data:"2025-02-12", tipo:"ASO Admissional",   descricao:"Glicemia em Jejum",       empresa:"Trama",                 paciente:"Thiago B2.",  status:"Realizado" },
  { data:"2025-02-13", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"WJ Decor",              paciente:"Ursula C2.",  status:"Realizado" },
  { data:"2025-02-14", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"ABS Infraestrutura",    paciente:"Vinicius D2.",status:"Realizado" },
  { data:"2025-02-17", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"Brasilquímica",         paciente:"Wanda E2.",   status:"Realizado" },
  { data:"2025-02-18", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"CLOMA Funilaria",       paciente:"Xavier F2.",  status:"Realizado" },
  { data:"2025-02-19", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"Don Pepper",            paciente:"Yasmin G2.",  status:"Realizado" },
  { data:"2025-02-20", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Fundição Garra",        paciente:"Zé H2.",      status:"Realizado" },
  { data:"2025-02-21", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Alice I2.",   status:"Realizado" },
  { data:"2025-02-24", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Haras Meirelles",       paciente:"Bruno J2.",   status:"Realizado" },
  { data:"2025-02-25", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Célia K2.",   status:"Realizado" },
  { data:"2025-02-26", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Multi-Grama Paisagismo",paciente:"Davi L2.",    status:"Realizado" },
  { data:"2025-02-27", tipo:"Coleta Laboratorial",descricao:"Hemograma Completo",     empresa:"Souza Arantes",         paciente:"Emília M2.",  status:"Realizado" },
  { data:"2025-02-28", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Fábio N2.",   status:"Realizado" },

  // ---- MARÇO 2025 ----
  { data:"2025-03-03", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"ABS Infraestrutura",    paciente:"Gabi O2.",    status:"Realizado" },
  { data:"2025-03-03", tipo:"ASO Admissional",   descricao:"Acuidade Visual",         empresa:"ABS Infraestrutura",    paciente:"Gabi O2.",    status:"Realizado" },
  { data:"2025-03-04", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Brasilquímica",         paciente:"Hugo P2.",    status:"Realizado" },
  { data:"2025-03-05", tipo:"ASO Periódico",     descricao:"Espirometria",            empresa:"CLOMA Funilaria",       paciente:"Ingrid Q2.",  status:"Realizado" },
  { data:"2025-03-06", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Don Pepper",            paciente:"Jonas R2.",   status:"Realizado" },
  { data:"2025-03-07", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Fundição Garra",        paciente:"Kátia S2.",   status:"Realizado" },
  { data:"2025-03-10", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"GM Empreendimentos",    paciente:"Leonardo T2.",status:"Realizado" },
  { data:"2025-03-11", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Haras Meirelles",       paciente:"Mônica U2.",  status:"Realizado" },
  { data:"2025-03-12", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Natan V2.",   status:"Realizado" },
  { data:"2025-03-13", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"Multi-Grama Paisagismo",paciente:"Odete W2.",   status:"Realizado" },
  { data:"2025-03-14", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"Souza Arantes",         paciente:"Pedro X2.",   status:"Realizado" },
  { data:"2025-03-17", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"TC Consult",            paciente:"Quinta Y2.",  status:"Realizado" },
  { data:"2025-03-18", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Trama",                 paciente:"Rafael Z2.",  status:"Realizado" },
  { data:"2025-03-18", tipo:"ASO Periódico",     descricao:"Colesterol Total",        empresa:"Trama",                 paciente:"Rafael Z2.",  status:"Realizado" },
  { data:"2025-03-19", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"WJ Decor",              paciente:"Sabrina A3.", status:"Realizado" },
  { data:"2025-03-20", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"ABS Infraestrutura",    paciente:"Tadeu B3.",   status:"Realizado" },
  { data:"2025-03-21", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"Brasilquímica",         paciente:"Úrsula C3.",  status:"Realizado" },
  { data:"2025-03-24", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"CLOMA Funilaria",       paciente:"Vagner D3.",  status:"Realizado" },
  { data:"2025-03-25", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Don Pepper",            paciente:"Wesley E3.",  status:"Realizado" },
  { data:"2025-03-26", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Fundição Garra",        paciente:"Xena F3.",    status:"Realizado" },
  { data:"2025-03-27", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"GM Empreendimentos",    paciente:"Yeda G3.",    status:"Realizado" },
  { data:"2025-03-28", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Haras Meirelles",       paciente:"Zeca H3.",    status:"Realizado" },
  { data:"2025-03-31", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Alice I3.",   status:"Realizado" },

  // ---- ABRIL 2025 ----
  { data:"2025-04-01", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Multi-Grama Paisagismo",paciente:"Bruno J3.",   status:"Realizado" },
  { data:"2025-04-02", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Souza Arantes",         paciente:"Carla K3.",   status:"Realizado" },
  { data:"2025-04-03", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"TC Consult",            paciente:"Daniel L3.",  status:"Realizado" },
  { data:"2025-04-04", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Trama",                 paciente:"Eliane M3.",  status:"Realizado" },
  { data:"2025-04-07", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"WJ Decor",              paciente:"Fausto N3.",  status:"Realizado" },
  { data:"2025-04-08", tipo:"ASO Demissional",   descricao:"Raio-X de Tórax",         empresa:"ABS Infraestrutura",    paciente:"Gema O3.",    status:"Realizado" },
  { data:"2025-04-09", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Hélio P3.",   status:"Realizado" },
  { data:"2025-04-09", tipo:"ASO Admissional",   descricao:"Acuidade Visual",         empresa:"Brasilquímica",         paciente:"Hélio P3.",   status:"Realizado" },
  { data:"2025-04-10", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"CLOMA Funilaria",       paciente:"Ísis Q3.",    status:"Realizado" },
  { data:"2025-04-11", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Don Pepper",            paciente:"João R3.",    status:"Realizado" },
  { data:"2025-04-14", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Fundição Garra",        paciente:"Keila S3.",   status:"Realizado" },
  { data:"2025-04-15", tipo:"ASO Periódico",     descricao:"Espirometria",            empresa:"GM Empreendimentos",    paciente:"Luiz T3.",    status:"Realizado" },
  { data:"2025-04-16", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"Haras Meirelles",       paciente:"Marta U3.",   status:"Realizado" },
  { data:"2025-04-17", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Nilton V3.",  status:"Realizado" },
  { data:"2025-04-22", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Multi-Grama Paisagismo",paciente:"Olga W3.",    status:"Realizado" },
  { data:"2025-04-23", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Souza Arantes",         paciente:"Plínio X3.",  status:"Realizado" },
  { data:"2025-04-24", tipo:"ASO Admissional",   descricao:"Raio-X de Tórax",         empresa:"TC Consult",            paciente:"Queila Y3.",  status:"Realizado" },
  { data:"2025-04-25", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"Trama",                 paciente:"Rui Z3.",     status:"Realizado" },
  { data:"2025-04-28", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"WJ Decor",              paciente:"Sara A4.",    status:"Realizado" },
  { data:"2025-04-29", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"ABS Infraestrutura",    paciente:"Toni B4.",    status:"Realizado" },
  { data:"2025-04-30", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Brasilquímica",         paciente:"Ula C4.",     status:"Realizado" },

  // ---- MAIO 2025 ----
  { data:"2025-05-02", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"CLOMA Funilaria",       paciente:"Vera D4.",    status:"Realizado" },
  { data:"2025-05-05", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Don Pepper",            paciente:"Walter E4.",  status:"Realizado" },
  { data:"2025-05-06", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Fundição Garra",        paciente:"Xandra F4.",  status:"Realizado" },
  { data:"2025-05-07", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Yasmim G4.",  status:"Realizado" },
  { data:"2025-05-07", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"GM Empreendimentos",    paciente:"Yasmim G4.",  status:"Realizado" },
  { data:"2025-05-08", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"Haras Meirelles",       paciente:"Zilda H4.",   status:"Realizado" },
  { data:"2025-05-09", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"Mega Impress",          paciente:"André I4.",   status:"Realizado" },
  { data:"2025-05-12", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Multi-Grama Paisagismo",paciente:"Bea J4.",     status:"Realizado" },
  { data:"2025-05-13", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Souza Arantes",         paciente:"Cid K4.",     status:"Realizado" },
  { data:"2025-05-14", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"TC Consult",            paciente:"Dina L4.",    status:"Realizado" },
  { data:"2025-05-15", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Trama",                 paciente:"Edu M4.",     status:"Realizado" },
  { data:"2025-05-16", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"WJ Decor",              paciente:"Fifi N4.",    status:"Realizado" },
  { data:"2025-05-19", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"ABS Infraestrutura",    paciente:"Gino O4.",    status:"Realizado" },
  { data:"2025-05-20", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Brasilquímica",         paciente:"Hana P4.",    status:"Realizado" },
  { data:"2025-05-21", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"CLOMA Funilaria",       paciente:"Ivan Q4.",    status:"Realizado" },
  { data:"2025-05-22", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"Don Pepper",            paciente:"Jana R4.",    status:"Realizado" },
  { data:"2025-05-23", tipo:"ASO Periódico",     descricao:"Espirometria",            empresa:"Fundição Garra",        paciente:"Kurt S4.",    status:"Realizado" },
  { data:"2025-05-26", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Lena T4.",    status:"Realizado" },
  { data:"2025-05-27", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Haras Meirelles",       paciente:"Milo U4.",    status:"Realizado" },
  { data:"2025-05-28", tipo:"Coleta Laboratorial",descricao:"Hemograma Completo",     empresa:"Mega Impress",          paciente:"Nina V4.",    status:"Realizado" },
  { data:"2025-05-29", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Multi-Grama Paisagismo",paciente:"Otto W4.",    status:"Realizado" },
  { data:"2025-05-30", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"Souza Arantes",         paciente:"Pia X4.",     status:"Realizado" },

  // ---- JUNHO 2025 ----
  { data:"2025-06-02", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Quin Y4.",    status:"Realizado" },
  { data:"2025-06-03", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Trama",                 paciente:"Rex Z4.",     status:"Realizado" },
  { data:"2025-06-04", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"WJ Decor",              paciente:"Sol A5.",     status:"Realizado" },
  { data:"2025-06-05", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"ABS Infraestrutura",    paciente:"Tim B5.",     status:"Realizado" },
  { data:"2025-06-05", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"ABS Infraestrutura",    paciente:"Tim B5.",     status:"Realizado" },
  { data:"2025-06-06", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"Brasilquímica",         paciente:"Uma C5.",     status:"Realizado" },
  { data:"2025-06-09", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"CLOMA Funilaria",       paciente:"Van D5.",     status:"Realizado" },
  { data:"2025-06-10", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Don Pepper",            paciente:"Wil E5.",     status:"Realizado" },
  { data:"2025-06-11", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Fundição Garra",        paciente:"Xica F5.",    status:"Realizado" },
  { data:"2025-06-12", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"GM Empreendimentos",    paciente:"Yuri G5.",    status:"Realizado" },
  { data:"2025-06-13", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Haras Meirelles",       paciente:"Zara H5.",    status:"Realizado" },
  { data:"2025-06-16", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"Mega Impress",          paciente:"Abel I5.",    status:"Realizado" },
  { data:"2025-06-17", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Multi-Grama Paisagismo",paciente:"Beti J5.",    status:"Realizado" },
  { data:"2025-06-18", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Souza Arantes",         paciente:"Caio K5.",    status:"Realizado" },
  { data:"2025-06-19", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"TC Consult",            paciente:"Dora L5.",    status:"Realizado" },
  { data:"2025-06-20", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"Trama",                 paciente:"Edu M5.",     status:"Realizado" },
  { data:"2025-06-23", tipo:"ASO Periódico",     descricao:"Espirometria",            empresa:"WJ Decor",              paciente:"Fani N5.",    status:"Realizado" },
  { data:"2025-06-24", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"ABS Infraestrutura",    paciente:"Guga O5.",    status:"Realizado" },
  { data:"2025-06-25", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Brasilquímica",         paciente:"Hebe P5.",    status:"Realizado" },
  { data:"2025-06-26", tipo:"Coleta Laboratorial",descricao:"Hemograma Completo",     empresa:"CLOMA Funilaria",       paciente:"Inês Q5.",    status:"Realizado" },
  { data:"2025-06-27", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Don Pepper",            paciente:"Jair R5.",    status:"Realizado" },
  { data:"2025-06-30", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"Fundição Garra",        paciente:"Keka S5.",    status:"Realizado" },

  // ---- JULHO 2025 ----
  { data:"2025-07-01", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Lara T5.",    status:"Realizado" },
  { data:"2025-07-02", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Haras Meirelles",       paciente:"Manu U5.",    status:"Realizado" },
  { data:"2025-07-03", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Mega Impress",          paciente:"Nelo V5.",    status:"Realizado" },
  { data:"2025-07-04", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Multi-Grama Paisagismo",paciente:"Ora W5.",     status:"Realizado" },
  { data:"2025-07-07", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Souza Arantes",         paciente:"Pita X5.",    status:"Realizado" },
  { data:"2025-07-08", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"TC Consult",            paciente:"Quim Y5.",    status:"Realizado" },
  { data:"2025-07-09", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Trama",                 paciente:"Rita Z5.",    status:"Realizado" },
  { data:"2025-07-09", tipo:"ASO Admissional",   descricao:"Acuidade Visual",         empresa:"Trama",                 paciente:"Rita Z5.",    status:"Realizado" },
  { data:"2025-07-10", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"WJ Decor",              paciente:"Saul A6.",    status:"Realizado" },
  { data:"2025-07-11", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"ABS Infraestrutura",    paciente:"Teca B6.",    status:"Realizado" },
  { data:"2025-07-14", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Urso C6.",    status:"Realizado" },
  { data:"2025-07-15", tipo:"ASO Periódico",     descricao:"Colesterol Total",        empresa:"CLOMA Funilaria",       paciente:"Vera D6.",    status:"Realizado" },
  { data:"2025-07-16", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Don Pepper",            paciente:"Will E6.",    status:"Realizado" },
  { data:"2025-07-17", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"Fundição Garra",        paciente:"Xia F6.",     status:"Realizado" },
  { data:"2025-07-18", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"GM Empreendimentos",    paciente:"York G6.",    status:"Realizado" },
  { data:"2025-07-21", tipo:"ASO Periódico",     descricao:"Espirometria",            empresa:"Haras Meirelles",       paciente:"Zita H6.",    status:"Realizado" },
  { data:"2025-07-22", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"Mega Impress",          paciente:"Adão I6.",    status:"Realizado" },
  { data:"2025-07-23", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Multi-Grama Paisagismo",paciente:"Bela J6.",    status:"Realizado" },
  { data:"2025-07-24", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Souza Arantes",         paciente:"Ceci K6.",    status:"Realizado" },
  { data:"2025-07-25", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"TC Consult",            paciente:"Deco L6.",    status:"Realizado" },
  { data:"2025-07-28", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Trama",                 paciente:"Ema M6.",     status:"Realizado" },
  { data:"2025-07-29", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"WJ Decor",              paciente:"Fado N6.",    status:"Realizado" },
  { data:"2025-07-30", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"ABS Infraestrutura",    paciente:"Gaia O6.",    status:"Realizado" },
  { data:"2025-07-31", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Hiro P6.",    status:"Realizado" },

  // ---- AGOSTO 2025 ----
  { data:"2025-08-01", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"CLOMA Funilaria",       paciente:"Iara Q6.",    status:"Realizado" },
  { data:"2025-08-04", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Don Pepper",            paciente:"Juca R6.",    status:"Realizado" },
  { data:"2025-08-05", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"Fundição Garra",        paciente:"Kiko S6.",    status:"Realizado" },
  { data:"2025-08-06", tipo:"ASO Periódico",     descricao:"Espirometria",            empresa:"GM Empreendimentos",    paciente:"Lila T6.",    status:"Realizado" },
  { data:"2025-08-07", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Haras Meirelles",       paciente:"Mimo U6.",    status:"Realizado" },
  { data:"2025-08-07", tipo:"ASO Admissional",   descricao:"Acuidade Visual",         empresa:"Haras Meirelles",       paciente:"Mimo U6.",    status:"Realizado" },
  { data:"2025-08-08", tipo:"ASO Demissional",   descricao:"Raio-X de Tórax",         empresa:"Mega Impress",          paciente:"Nena V6.",    status:"Realizado" },
  { data:"2025-08-11", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Multi-Grama Paisagismo",paciente:"Omar W6.",    status:"Realizado" },
  { data:"2025-08-12", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Souza Arantes",         paciente:"Paco X6.",    status:"Realizado" },
  { data:"2025-08-13", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Qara Y6.",    status:"Realizado" },
  { data:"2025-08-14", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"Trama",                 paciente:"Rosa Z6.",    status:"Realizado" },
  { data:"2025-08-15", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"WJ Decor",              paciente:"Samir A7.",   status:"Realizado" },
  { data:"2025-08-18", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"ABS Infraestrutura",    paciente:"Tito B7.",    status:"Realizado" },
  { data:"2025-08-19", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Brasilquímica",         paciente:"Uva C7.",     status:"Realizado" },
  { data:"2025-08-20", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"CLOMA Funilaria",       paciente:"Vida D7.",    status:"Realizado" },
  { data:"2025-08-21", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"Don Pepper",            paciente:"Wena E7.",    status:"Realizado" },
  { data:"2025-08-22", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Fundição Garra",        paciente:"Xilo F7.",    status:"Realizado" },
  { data:"2025-08-25", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"GM Empreendimentos",    paciente:"Yoko G7.",    status:"Realizado" },
  { data:"2025-08-26", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"Haras Meirelles",       paciente:"Zé H7.",      status:"Realizado" },
  { data:"2025-08-27", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Mega Impress",          paciente:"Aldo I7.",    status:"Realizado" },
  { data:"2025-08-28", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Multi-Grama Paisagismo",paciente:"Babi J7.",    status:"Realizado" },
  { data:"2025-08-29", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Souza Arantes",         paciente:"Caito K7.",   status:"Realizado" },

  // ---- SETEMBRO 2025 ----
  { data:"2025-09-01", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Dabi L7.",    status:"Realizado" },
  { data:"2025-09-02", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Trama",                 paciente:"Ega M7.",     status:"Realizado" },
  { data:"2025-09-03", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"WJ Decor",              paciente:"Filo N7.",    status:"Realizado" },
  { data:"2025-09-04", tipo:"ASO Periódico",     descricao:"Espirometria",            empresa:"ABS Infraestrutura",    paciente:"Gico O7.",    status:"Realizado" },
  { data:"2025-09-05", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Helo P7.",    status:"Realizado" },
  { data:"2025-09-05", tipo:"ASO Admissional",   descricao:"Acuidade Visual",         empresa:"Brasilquímica",         paciente:"Helo P7.",    status:"Realizado" },
  { data:"2025-09-08", tipo:"ASO Demissional",   descricao:"Raio-X de Tórax",         empresa:"CLOMA Funilaria",       paciente:"Iana Q7.",    status:"Realizado" },
  { data:"2025-09-09", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Don Pepper",            paciente:"Joca R7.",    status:"Realizado" },
  { data:"2025-09-10", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Fundição Garra",        paciente:"Kira S7.",    status:"Realizado" },
  { data:"2025-09-11", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Luna T7.",    status:"Realizado" },
  { data:"2025-09-12", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"Haras Meirelles",       paciente:"Mike U7.",    status:"Realizado" },
  { data:"2025-09-15", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Nile V7.",    status:"Realizado" },
  { data:"2025-09-16", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Multi-Grama Paisagismo",paciente:"Oleo W7.",    status:"Realizado" },
  { data:"2025-09-17", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Souza Arantes",         paciente:"Pão X7.",     status:"Realizado" },
  { data:"2025-09-18", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Quê Y7.",     status:"Realizado" },
  { data:"2025-09-19", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"Trama",                 paciente:"Remi Z7.",    status:"Realizado" },
  { data:"2025-09-22", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"WJ Decor",              paciente:"Siri A8.",    status:"Realizado" },
  { data:"2025-09-23", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"ABS Infraestrutura",    paciente:"Tuca B8.",    status:"Realizado" },
  { data:"2025-09-24", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Uiri C8.",    status:"Realizado" },
  { data:"2025-09-25", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"CLOMA Funilaria",       paciente:"Vani D8.",    status:"Realizado" },
  { data:"2025-09-26", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Don Pepper",            paciente:"Wili E8.",    status:"Realizado" },
  { data:"2025-09-29", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Fundição Garra",        paciente:"Xico F8.",    status:"Realizado" },
  { data:"2025-09-30", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"GM Empreendimentos",    paciente:"Yema G8.",    status:"Realizado" },

  // ---- OUTUBRO 2025 ----
  { data:"2025-10-01", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"Haras Meirelles",       paciente:"Zilo H8.",    status:"Realizado" },
  { data:"2025-10-02", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Aret I8.",    status:"Realizado" },
  { data:"2025-10-03", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Multi-Grama Paisagismo",paciente:"Beto J8.",    status:"Realizado" },
  { data:"2025-10-06", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Souza Arantes",         paciente:"Canu K8.",    status:"Realizado" },
  { data:"2025-10-07", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Dara L8.",    status:"Realizado" },
  { data:"2025-10-08", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Trama",                 paciente:"Eloy M8.",    status:"Realizado" },
  { data:"2025-10-09", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"WJ Decor",              paciente:"Felo N8.",    status:"Realizado" },
  { data:"2025-10-09", tipo:"ASO Admissional",   descricao:"Raio-X de Tórax",         empresa:"WJ Decor",              paciente:"Felo N8.",    status:"Realizado" },
  { data:"2025-10-10", tipo:"ASO Periódico",     descricao:"Colesterol Total",        empresa:"ABS Infraestrutura",    paciente:"Gele O8.",    status:"Realizado" },
  { data:"2025-10-13", tipo:"Coleta Laboratorial",descricao:"Hemograma Completo",     empresa:"Brasilquímica",         paciente:"Hola P8.",    status:"Realizado" },
  { data:"2025-10-14", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"CLOMA Funilaria",       paciente:"Inka Q8.",    status:"Realizado" },
  { data:"2025-10-15", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Don Pepper",            paciente:"Jero R8.",    status:"Realizado" },
  { data:"2025-10-16", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Fundição Garra",        paciente:"Kero S8.",    status:"Realizado" },
  { data:"2025-10-17", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"GM Empreendimentos",    paciente:"Liro T8.",    status:"Realizado" },
  { data:"2025-10-20", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Haras Meirelles",       paciente:"Mato U8.",    status:"Realizado" },
  { data:"2025-10-21", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Mega Impress",          paciente:"Nado V8.",    status:"Realizado" },
  { data:"2025-10-22", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Multi-Grama Paisagismo",paciente:"Oito W8.",    status:"Realizado" },
  { data:"2025-10-23", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Souza Arantes",         paciente:"Polo X8.",    status:"Realizado" },
  { data:"2025-10-24", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Qua Y8.",     status:"Realizado" },
  { data:"2025-10-27", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Trama",                 paciente:"Reba Z8.",    status:"Realizado" },
  { data:"2025-10-28", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"WJ Decor",              paciente:"Salo A9.",    status:"Realizado" },
  { data:"2025-10-29", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"ABS Infraestrutura",    paciente:"Tira B9.",    status:"Realizado" },
  { data:"2025-10-30", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"Brasilquímica",         paciente:"Ulna C9.",    status:"Realizado" },
  { data:"2025-10-31", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"CLOMA Funilaria",       paciente:"Vira D9.",    status:"Realizado" },

  // ---- NOVEMBRO 2025 ----
  { data:"2025-11-03", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Don Pepper",            paciente:"Wisa E9.",    status:"Realizado" },
  { data:"2025-11-04", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Fundição Garra",        paciente:"Xala F9.",    status:"Realizado" },
  { data:"2025-11-05", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"GM Empreendimentos",    paciente:"Yamo G9.",    status:"Realizado" },
  { data:"2025-11-05", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Yamo G9.",    status:"Realizado" },
  { data:"2025-11-06", tipo:"ASO Demissional",   descricao:"Raio-X de Tórax",         empresa:"Haras Meirelles",       paciente:"Zago H9.",    status:"Realizado" },
  { data:"2025-11-07", tipo:"Coleta Laboratorial",descricao:"Hemograma Completo",     empresa:"Mega Impress",          paciente:"Alce I9.",    status:"Realizado" },
  { data:"2025-11-10", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Multi-Grama Paisagismo",paciente:"Boca J9.",    status:"Realizado" },
  { data:"2025-11-11", tipo:"ASO Periódico",     descricao:"Colesterol Total",        empresa:"Souza Arantes",         paciente:"Cela K9.",    status:"Realizado" },
  { data:"2025-11-12", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Dara L9.",    status:"Realizado" },
  { data:"2025-11-13", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Trama",                 paciente:"Eira M9.",    status:"Realizado" },
  { data:"2025-11-14", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"WJ Decor",              paciente:"Fora N9.",    status:"Realizado" },
  { data:"2025-11-17", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"ABS Infraestrutura",    paciente:"Gaia O9.",    status:"Realizado" },
  { data:"2025-11-18", tipo:"ASO Admissional",   descricao:"Raio-X de Tórax",         empresa:"Brasilquímica",         paciente:"Hana P9.",    status:"Realizado" },
  { data:"2025-11-19", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"CLOMA Funilaria",       paciente:"Inei Q9.",    status:"Realizado" },
  { data:"2025-11-20", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Don Pepper",            paciente:"Japa R9.",    status:"Realizado" },
  { data:"2025-11-21", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Fundição Garra",        paciente:"Kita S9.",    status:"Realizado" },
  { data:"2025-11-24", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Leda T9.",    status:"Realizado" },
  { data:"2025-11-25", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"Haras Meirelles",       paciente:"Mira U9.",    status:"Realizado" },
  { data:"2025-11-26", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Nair V9.",    status:"Realizado" },
  { data:"2025-11-26", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Mega Impress",          paciente:"Nair V9.",    status:"Realizado" },
  { data:"2025-11-27", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"Multi-Grama Paisagismo",paciente:"Otar W9.",    status:"Realizado" },
  { data:"2025-11-28", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Souza Arantes",         paciente:"Pela X9.",    status:"Realizado" },

  // ---- DEZEMBRO 2025 ----
  { data:"2025-12-01", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Quim Y9.",    status:"Realizado" },
  { data:"2025-12-02", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Trama",                 paciente:"Robo Z9.",    status:"Realizado" },
  { data:"2025-12-03", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"WJ Decor",              paciente:"Solo AA.",    status:"Realizado" },
  { data:"2025-12-04", tipo:"Coleta Laboratorial",descricao:"Hemograma Completo",     empresa:"ABS Infraestrutura",    paciente:"Tara BB.",    status:"Realizado" },
  { data:"2025-12-05", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Uara CC.",    status:"Realizado" },
  { data:"2025-12-08", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"CLOMA Funilaria",       paciente:"Viga DD.",    status:"Realizado" },
  { data:"2025-12-09", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"Don Pepper",            paciente:"Wata EE.",    status:"Realizado" },
  { data:"2025-12-10", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Fundição Garra",        paciente:"Xale FF.",    status:"Realizado" },
  { data:"2025-12-11", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Yama GG.",    status:"Realizado" },
  { data:"2025-12-12", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"Haras Meirelles",       paciente:"Zara HH.",    status:"Realizado" },
  { data:"2025-12-15", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Aloa II.",    status:"Realizado" },
  { data:"2025-12-15", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Mega Impress",          paciente:"Aloa II.",    status:"Realizado" },
  { data:"2025-12-16", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Multi-Grama Paisagismo",paciente:"Bira JJ.",    status:"Realizado" },
  { data:"2025-12-17", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Souza Arantes",         paciente:"Cito KK.",    status:"Realizado" },
  { data:"2025-12-18", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"TC Consult",            paciente:"Dara LL.",    status:"Realizado" },
  { data:"2025-12-19", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Trama",                 paciente:"Enol MM.",    status:"Realizado" },
  { data:"2025-12-22", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"WJ Decor",              paciente:"Faro NN.",    status:"Realizado" },
  { data:"2025-12-23", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"ABS Infraestrutura",    paciente:"Gama OO.",    status:"Realizado" },

  // ---- JANEIRO 2026 ----
  { data:"2026-01-05", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Hilo PP.",    status:"Realizado" },
  { data:"2026-01-06", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"CLOMA Funilaria",       paciente:"Irma QQ.",    status:"Realizado" },
  { data:"2026-01-06", tipo:"ASO Periódico",     descricao:"Colesterol Total",        empresa:"CLOMA Funilaria",       paciente:"Irma QQ.",    status:"Realizado" },
  { data:"2026-01-07", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Don Pepper",            paciente:"Jelo RR.",    status:"Realizado" },
  { data:"2026-01-08", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Fundição Garra",        paciente:"Kana SS.",    status:"Realizado" },
  { data:"2026-01-09", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Lara TT.",    status:"Realizado" },
  { data:"2026-01-12", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Haras Meirelles",       paciente:"Mina UU.",    status:"Realizado" },
  { data:"2026-01-12", tipo:"ASO Admissional",   descricao:"Raio-X de Tórax",         empresa:"Haras Meirelles",       paciente:"Mina UU.",    status:"Realizado" },
  { data:"2026-01-13", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Mega Impress",          paciente:"Nora VV.",    status:"Realizado" },
  { data:"2026-01-14", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"Multi-Grama Paisagismo",paciente:"Orin WW.",    status:"Realizado" },
  { data:"2026-01-15", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Souza Arantes",         paciente:"Pati XX.",    status:"Realizado" },
  { data:"2026-01-16", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"TC Consult",            paciente:"Quin YY.",    status:"Realizado" },
  { data:"2026-01-19", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Trama",                 paciente:"Riri ZZ.",    status:"Realizado" },
  { data:"2026-01-20", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"WJ Decor",              paciente:"Siga A10.",   status:"Realizado" },
  { data:"2026-01-21", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"ABS Infraestrutura",    paciente:"Tana B10.",   status:"Realizado" },
  { data:"2026-01-22", tipo:"ASO Demissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Uber C10.",   status:"Realizado" },
  { data:"2026-01-23", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"CLOMA Funilaria",       paciente:"Venu D10.",   status:"Realizado" },
  { data:"2026-01-26", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Don Pepper",            paciente:"Wira E10.",   status:"Realizado" },
  { data:"2026-01-27", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Fundição Garra",        paciente:"Xati F10.",   status:"Realizado" },
  { data:"2026-01-28", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"GM Empreendimentos",    paciente:"Yuna G10.",   status:"Realizado" },
  { data:"2026-01-29", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Haras Meirelles",       paciente:"Zeta H10.",   status:"Realizado" },
  { data:"2026-01-30", tipo:"ASO Retorno",       descricao:"Espirometria",            empresa:"Mega Impress",          paciente:"Alan I10.",   status:"Realizado" },

  // ---- FEVEREIRO 2026 ----
  { data:"2026-02-02", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Multi-Grama Paisagismo",paciente:"Bela J10.",   status:"Realizado" },
  { data:"2026-02-03", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Souza Arantes",         paciente:"Cuca K10.",   status:"Realizado" },
  { data:"2026-02-04", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"TC Consult",            paciente:"Davi L10.",   status:"Realizado" },
  { data:"2026-02-05", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Trama",                 paciente:"Eloa M10.",   status:"Realizado" },
  { data:"2026-02-05", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Trama",                 paciente:"Eloa M10.",   status:"Realizado" },
  { data:"2026-02-06", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"WJ Decor",              paciente:"Figo N10.",   status:"Realizado" },
  { data:"2026-02-09", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"ABS Infraestrutura",    paciente:"Gelo O10.",   status:"Realizado" },
  { data:"2026-02-10", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Hila P10.",   status:"Realizado" },
  { data:"2026-02-11", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"CLOMA Funilaria",       paciente:"Inca Q10.",   status:"Realizado" },
  { data:"2026-02-12", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Don Pepper",            paciente:"Jela R10.",   status:"Realizado" },
  { data:"2026-02-13", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"Fundição Garra",        paciente:"Kola S10.",   status:"Realizado" },
  { data:"2026-02-16", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Luma T10.",   status:"Realizado" },
  { data:"2026-02-17", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Haras Meirelles",       paciente:"Mila U10.",   status:"Realizado" },
  { data:"2026-02-18", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Mega Impress",          paciente:"Nona V10.",   status:"Realizado" },
  { data:"2026-02-19", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"Multi-Grama Paisagismo",paciente:"Orca W10.",   status:"Realizado" },
  { data:"2026-02-20", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"Souza Arantes",         paciente:"Palo X10.",   status:"Realizado" },
  { data:"2026-02-23", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"TC Consult",            paciente:"Quba Y10.",   status:"Realizado" },
  { data:"2026-02-24", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Trama",                 paciente:"Rula Z10.",   status:"Realizado" },
  { data:"2026-02-25", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"WJ Decor",              paciente:"Sara AA2.",   status:"Realizado" },
  { data:"2026-02-26", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"ABS Infraestrutura",    paciente:"Tilo BB2.",   status:"Realizado" },
  { data:"2026-02-27", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Brasilquímica",         paciente:"Ulna CC2.",   status:"Realizado" },

  // ---- MARÇO 2026 ----
  { data:"2026-03-02", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"CLOMA Funilaria",       paciente:"Vida DD2.",   status:"Realizado" },
  { data:"2026-03-03", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Don Pepper",            paciente:"Wiga EE2.",   status:"Realizado" },
  { data:"2026-03-03", tipo:"ASO Periódico",     descricao:"Colesterol Total",        empresa:"Don Pepper",            paciente:"Wiga EE2.",   status:"Realizado" },
  { data:"2026-03-04", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"Fundição Garra",        paciente:"Xula FF2.",   status:"Realizado" },
  { data:"2026-03-05", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"GM Empreendimentos",    paciente:"Yolo GG2.",   status:"Realizado" },
  { data:"2026-03-06", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Yolo GG2.",   status:"Realizado" },
  { data:"2026-03-09", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Haras Meirelles",       paciente:"Zara HH2.",   status:"Realizado" },
  { data:"2026-03-10", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Mega Impress",          paciente:"Abas II2.",   status:"Realizado" },
  { data:"2026-03-11", tipo:"ASO Demissional",   descricao:"Raio-X de Tórax",         empresa:"Multi-Grama Paisagismo",paciente:"Belu JJ2.",   status:"Realizado" },
  { data:"2026-03-12", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Souza Arantes",         paciente:"Ceri KK2.",   status:"Realizado" },
  { data:"2026-03-13", tipo:"Coleta Laboratorial",descricao:"Hemograma Completo",     empresa:"TC Consult",            paciente:"Demi LL2.",   status:"Realizado" },
  { data:"2026-03-16", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"Trama",                 paciente:"Erni MM2.",   status:"Realizado" },
  { data:"2026-03-17", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"WJ Decor",              paciente:"Fala NN2.",   status:"Realizado" },
  { data:"2026-03-18", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"ABS Infraestrutura",    paciente:"Gala OO2.",   status:"Realizado" },
  { data:"2026-03-19", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Brasilquímica",         paciente:"Haru PP2.",   status:"Realizado" },
  { data:"2026-03-20", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"CLOMA Funilaria",       paciente:"Inke QQ2.",   status:"Realizado" },
  { data:"2026-03-23", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"Don Pepper",            paciente:"Jebe RR2.",   status:"Realizado" },
  { data:"2026-03-24", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Fundição Garra",        paciente:"Kare SS2.",   status:"Realizado" },
  { data:"2026-03-24", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Fundição Garra",        paciente:"Kare SS2.",   status:"Realizado" },
  { data:"2026-03-25", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"GM Empreendimentos",    paciente:"Lube TT2.",   status:"Realizado" },
  { data:"2026-03-26", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Haras Meirelles",       paciente:"Magi UU2.",   status:"Realizado" },
  { data:"2026-03-27", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Mega Impress",          paciente:"Napa VV2.",   status:"Realizado" },
  { data:"2026-03-30", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Multi-Grama Paisagismo",paciente:"Obra WW2.",   status:"Realizado" },
  { data:"2026-03-31", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Souza Arantes",         paciente:"Para XX2.",   status:"Realizado" },

  // ---- ABRIL 2026 ----
  { data:"2026-04-01", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"TC Consult",            paciente:"Quar YY2.",   status:"Realizado" },
  { data:"2026-04-02", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Trama",                 paciente:"Raca ZZ2.",   status:"Realizado" },
  { data:"2026-04-02", tipo:"ASO Admissional",   descricao:"Acuidade Visual",         empresa:"Trama",                 paciente:"Raca ZZ2.",   status:"Realizado" },
  { data:"2026-04-03", tipo:"ASO Periódico",     descricao:"Espirometria",            empresa:"WJ Decor",              paciente:"Saga A11.",   status:"Realizado" },
  { data:"2026-04-04", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"ABS Infraestrutura",    paciente:"Taga B11.",   status:"Realizado" },
  { data:"2026-04-07", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Brasilquímica",         paciente:"Uira C11.",   status:"Realizado" },
  { data:"2026-04-08", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"CLOMA Funilaria",       paciente:"Vibe D11.",   status:"Realizado" },
  { data:"2026-04-09", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Don Pepper",            paciente:"Wiki E11.",   status:"Realizado" },
  { data:"2026-04-10", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Fundição Garra",        paciente:"Xela F11.",   status:"Realizado" },
  { data:"2026-04-11", tipo:"Coleta Laboratorial",descricao:"Hemograma Completo",     empresa:"GM Empreendimentos",    paciente:"Yago G11.",   status:"Realizado" },
  { data:"2026-04-14", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Haras Meirelles",       paciente:"Zara H11.",   status:"Realizado" },
  { data:"2026-04-15", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Abel I11.",   status:"Realizado" },
  { data:"2026-04-16", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Multi-Grama Paisagismo",paciente:"Beca J11.",   status:"Realizado" },
  { data:"2026-04-17", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Souza Arantes",         paciente:"Cera K11.",   status:"Realizado" },
  { data:"2026-04-22", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"TC Consult",            paciente:"Daro L11.",   status:"Realizado" },
  { data:"2026-04-23", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Trama",                 paciente:"Elsa M11.",   status:"Realizado" },
  { data:"2026-04-23", tipo:"ASO Admissional",   descricao:"Raio-X de Tórax",         empresa:"Trama",                 paciente:"Elsa M11.",   status:"Realizado" },
  { data:"2026-04-24", tipo:"ASO Periódico",     descricao:"Colesterol Total",        empresa:"WJ Decor",              paciente:"Faro N11.",   status:"Realizado" },
  { data:"2026-04-25", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"ABS Infraestrutura",    paciente:"Gema O11.",   status:"Realizado" },
  { data:"2026-04-28", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Heca P11.",   status:"Realizado" },
  { data:"2026-04-29", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"CLOMA Funilaria",       paciente:"Inei Q11.",   status:"Realizado" },
  { data:"2026-04-30", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Don Pepper",            paciente:"Juca R11.",   status:"Realizado" },

  // ---- MAIO 2026 ----
  { data:"2026-05-02", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"Fundição Garra",        paciente:"Kala S11.",   status:"Realizado" },
  { data:"2026-05-05", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"GM Empreendimentos",    paciente:"Lena T11.",   status:"Realizado" },
  { data:"2026-05-05", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Lena T11.",   status:"Realizado" },
  { data:"2026-05-06", tipo:"Coleta Laboratorial",descricao:"Hemograma Completo",     empresa:"Haras Meirelles",       paciente:"Mira U11.",   status:"Realizado" },
  { data:"2026-05-07", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Nena V11.",   status:"Realizado" },
  { data:"2026-05-08", tipo:"ASO Periódico",     descricao:"Acuidade Visual",         empresa:"Multi-Grama Paisagismo",paciente:"Omar W11.",   status:"Realizado" },
  { data:"2026-05-09", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Souza Arantes",         paciente:"Pila X11.",   status:"Realizado" },
  { data:"2026-05-12", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"TC Consult",            paciente:"Quba Y11.",   status:"Realizado" },
  { data:"2026-05-13", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Trama",                 paciente:"Rana Z11.",   status:"Realizado" },
  { data:"2026-05-14", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"WJ Decor",              paciente:"Sara A12.",   status:"Realizado" },
  { data:"2026-05-15", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"ABS Infraestrutura",    paciente:"Tana B12.",   status:"Realizado" },
  { data:"2026-05-16", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Ubas C12.",   status:"Realizado" },
  { data:"2026-05-16", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Brasilquímica",         paciente:"Ubas C12.",   status:"Realizado" },
  { data:"2026-05-19", tipo:"ASO Periódico",     descricao:"Triglicerídeos",          empresa:"CLOMA Funilaria",       paciente:"Vira D12.",   status:"Realizado" },
  { data:"2026-05-20", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"Don Pepper",            paciente:"Wisa E12.",   status:"Realizado" },
  { data:"2026-05-21", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Fundição Garra",        paciente:"Xana F12.",   status:"Realizado" },
  { data:"2026-05-22", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"GM Empreendimentos",    paciente:"Yeda G12.",   status:"Realizado" },
  { data:"2026-05-23", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"Haras Meirelles",       paciente:"Zeal H12.",   status:"Realizado" },
  { data:"2026-05-26", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Mega Impress",          paciente:"Albo I12.",   status:"Realizado" },
  { data:"2026-05-27", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Multi-Grama Paisagismo",paciente:"Bela J12.",   status:"Realizado" },
  { data:"2026-05-28", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Souza Arantes",         paciente:"Cena K12.",   status:"Realizado" },
  { data:"2026-05-29", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"TC Consult",            paciente:"Dara L12.",   status:"Realizado" },
  { data:"2026-05-30", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Trama",                 paciente:"Elas M12.",   status:"Realizado" },

  // ---- JUNHO 2026 ----
  { data:"2026-06-02", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"WJ Decor",              paciente:"Febe N12.",   status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"WJ Decor",              paciente:"Febe N12.",   status:"Realizado" },
  { data:"2026-06-03", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"ABS Infraestrutura",    paciente:"Gila O12.",   status:"Realizado" },
  { data:"2026-06-04", tipo:"Coleta Laboratorial",descricao:"Glicemia em Jejum",      empresa:"Brasilquímica",         paciente:"Hula P12.",   status:"Realizado" },
  { data:"2026-06-05", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"CLOMA Funilaria",       paciente:"Iras Q12.",   status:"Realizado" },
  { data:"2026-06-06", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"Don Pepper",            paciente:"Jona R12.",   status:"Realizado" },
  { data:"2026-06-09", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"Fundição Garra",        paciente:"Kara S12.",   status:"Realizado" },
  { data:"2026-06-10", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"GM Empreendimentos",    paciente:"Lama T12.",   status:"Realizado" },
  { data:"2026-06-10", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"GM Empreendimentos",    paciente:"Lama T12.",   status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Retorno",       descricao:"Audiometria",             empresa:"Haras Meirelles",       paciente:"Mona U12.",   status:"Realizado" },
  { data:"2026-06-12", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"Mega Impress",          paciente:"Nuda V12.",   status:"Realizado" },
  { data:"2026-06-13", tipo:"Coleta Laboratorial",descricao:"Triglicerídeos",         empresa:"Multi-Grama Paisagismo",paciente:"Obra W12.",   status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Souza Arantes",         paciente:"Para X12.",   status:"Agendado" },
  { data:"2026-06-16", tipo:"ASO Admissional",   descricao:"Acuidade Visual",         empresa:"Souza Arantes",         paciente:"Para X12.",   status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico",     descricao:"Raio-X de Tórax",         empresa:"TC Consult",            paciente:"Quba Y12.",   status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Admissional",   descricao:"Espirometria",            empresa:"Trama",                 paciente:"Roja Z12.",   status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Admissional",   descricao:"Hemograma Completo",      empresa:"Trama",                 paciente:"Roja Z12.",   status:"Agendado" },
  { data:"2026-06-19", tipo:"ASO Periódico",     descricao:"Audiometria",             empresa:"WJ Decor",              paciente:"Siba A13.",   status:"Agendado" },
  { data:"2026-06-20", tipo:"Consulta Médica",   descricao:"Consulta Clínica Geral",  empresa:"ABS Infraestrutura",    paciente:"Toca B13.",   status:"Agendado" },
  { data:"2026-06-23", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Brasilquímica",         paciente:"Ulna C13.",   status:"Agendado" },
  { data:"2026-06-24", tipo:"ASO Periódico",     descricao:"Hemograma Completo",      empresa:"CLOMA Funilaria",       paciente:"Vera D13.",   status:"Agendado" },
  { data:"2026-06-25", tipo:"Coleta Laboratorial",descricao:"Colesterol Total",       empresa:"Don Pepper",            paciente:"Wena E13.",   status:"Agendado" },
  { data:"2026-06-26", tipo:"ASO Admissional",   descricao:"Audiometria",             empresa:"Fundição Garra",        paciente:"Xena F13.",   status:"Agendado" },
  { data:"2026-06-26", tipo:"ASO Admissional",   descricao:"Raio-X de Tórax",         empresa:"Fundição Garra",        paciente:"Xena F13.",   status:"Agendado" },
  { data:"2026-06-27", tipo:"ASO Demissional",   descricao:"Hemograma Completo",      empresa:"GM Empreendimentos",    paciente:"Yena G13.",   status:"Agendado" },
  { data:"2026-06-30", tipo:"ASO Admissional",   descricao:"Eletrocardiograma",       empresa:"Haras Meirelles",       paciente:"Zena H13.",   status:"Agendado" },
];

// Metadados de exibição para tipos de exames
const TIPO_CORES = {
  "ASO Admissional":    "#1a6e3c",
  "ASO Periódico":      "#2ecc71",
  "ASO Demissional":    "#e74c3c",
  "ASO Retorno":        "#f39c12",
  "Consulta Médica":    "#3498db",
  "Coleta Laboratorial":"#9b59b6",
};

const DESCRICAO_CORES = {
  "Audiometria":         "#1a6e3c",
  "Acuidade Visual":     "#27ae60",
  "Espirometria":        "#2980b9",
  "Hemograma Completo":  "#8e44ad",
  "Glicemia em Jejum":   "#e67e22",
  "Colesterol Total":    "#e74c3c",
  "Raio-X de Tórax":     "#16a085",
  "Triglicerídeos":      "#d35400",
  "Eletrocardiograma":   "#c0392b",
  "Acuidade Visual":     "#27ae60",
  "Consulta Clínica Geral": "#2c3e50",
};
